import type { BlockType, Template } from "./types";

/**
 * Single source of truth for every design in the collection.
 * The shared <InvitationRenderer /> is driven entirely by these objects,
 * so adding a design means adding one entry here (plus, if it needs a new
 * material, one block of CSS in styles/invitation.css).
 */

const DEFAULT_ORDER: BlockType[] = [
  "names",
  "invitation-line",
  "date",
  "time",
  "venue",
  "map",
  "rsvp",
  "vael-mark",
];

const ALL_FEATURES = ["seal", "map", "rsvp", "photo", "message"] as const;

export const templates: Template[] = [
  /* ------------------------------------------------------------------ FREE */
  {
    id: "ivory-ceremony",
    name: "Ivory Ceremony",
    access: "free",
    description: "Soft paper, silver light, and a quiet beginning.",
    theme: "ivory",
    palette: {
      background: "#F1EEE7",
      surface: "#FAF8F2",
      foreground: "#171719",
      muted: "#77736B",
      accent: "#A8A39A",
    },
    typography: "editorial-serif",
    layout: "classic",
    seal: "silver",
    material: "paper",
    stage: "#4F1622",
    motionStyle: "paper-reveal",
    blockOrder: DEFAULT_ORDER,
    features: [...ALL_FEATURES],
    i18n: { ar: { description: "ورق ناعم وضوء فضي وبداية هادئة." } },
  },
  {
    id: "noir-evening",
    name: "Noir Evening",
    access: "free",
    description: "Obsidian darkness for an unforgettable night.",
    theme: "noir",
    palette: {
      background: "#050506",
      surface: "#0E0E10",
      foreground: "#EDE8DC",
      muted: "#8C8778",
      accent: "#B7A98A",
    },
    typography: "didone",
    layout: "cinematic",
    seal: "obsidian",
    material: "obsidian",
    stage: "#2B2622",
    motionStyle: "quiet-fade",
    blockOrder: DEFAULT_ORDER,
    features: [...ALL_FEATURES, "animated-background"],
    i18n: { ar: { description: "عتمة الأوبسيديان لليلة لا تُنسى." } },
  },
  {
    id: "oud-garden",
    name: "Oud Garden",
    access: "free",
    description: "Warm sand, olive shadows, and golden geometry.",
    theme: "oud",
    palette: {
      background: "#D9C7A2",
      surface: "#E6D8BA",
      foreground: "#2B2A18",
      muted: "#6B6641",
      accent: "#9C7A2E",
    },
    typography: "humanist-serif",
    layout: "framed",
    seal: "gold",
    material: "sand-geometry",
    stage: "#3F3E22",
    motionStyle: "geometry-draw",
    blockOrder: DEFAULT_ORDER,
    features: [...ALL_FEATURES],
    i18n: { ar: { description: "رمال دافئة وظلال زيتونية وهندسة ذهبية." } },
  },
  {
    id: "linea",
    name: "Linea",
    access: "free",
    description: "Pure form, quiet type, and the beauty of restraint.",
    theme: "linea",
    palette: {
      background: "#F6F5F2",
      surface: "#F6F5F2",
      foreground: "#111111",
      muted: "#6A6A66",
      accent: "#111111",
    },
    typography: "modern-grotesk",
    layout: "minimal",
    seal: "none",
    material: "linen-line",
    stage: "#C9C5BB",
    motionStyle: "ink-fade",
    blockOrder: DEFAULT_ORDER,
    features: [...ALL_FEATURES],
    i18n: { ar: { description: "شكل خالص وخط هادئ وجمال الاكتفاء." } },
  },
  {
    id: "nacre",
    name: "Nacre",
    access: "free",
    description: "Pearl tones and soft edges for an intimate celebration.",
    theme: "nacre",
    palette: {
      background: "#EAE0E3",
      surface: "#F2EAEC",
      foreground: "#3A3139",
      muted: "#6F626A",
      accent: "#B99CA6",
    },
    typography: "editorial-serif",
    layout: "arch",
    seal: "pearl",
    material: "pearl",
    stage: "#6E5B66",
    motionStyle: "pearl-glow",
    blockOrder: DEFAULT_ORDER,
    features: [...ALL_FEATURES],
    i18n: { ar: { description: "درجات اللؤلؤ وحواف ناعمة لاحتفال حميم." } },
  },

  /* --------------------------------------------------------------- PREMIUM */
  {
    id: "moonlit-villa",
    name: "Moonlit Villa",
    access: "premium",
    description: "A cinematic invitation for an evening under the trees.",
    theme: "moonlit",
    palette: {
      background: "#0B1416",
      surface: "#102022",
      foreground: "#E8EDE6",
      muted: "#8FA29C",
      accent: "#CFC38E",
    },
    typography: "humanist-serif",
    layout: "cinematic",
    seal: "silver",
    material: "moonlit",
    stage: "#2C4144",
    motionStyle: "moon-rise",
    blockOrder: DEFAULT_ORDER,
    features: [...ALL_FEATURES, "animated-background"],
    i18n: { ar: { description: "دعوة سينمائية لأمسية تحت الأشجار." } },
  },
  {
    id: "palm-house",
    name: "Palm House",
    access: "premium",
    description: "Warm cream, botanical shadows, and garden light.",
    theme: "palm",
    palette: {
      background: "#EADFC8",
      surface: "#F0E7D3",
      foreground: "#2A2E20",
      muted: "#66634A",
      accent: "#6F7B4A",
    },
    typography: "editorial-serif",
    layout: "arch",
    seal: "gold",
    material: "palm-shadow",
    stage: "#B5A278",
    motionStyle: "botanical-shadow",
    blockOrder: DEFAULT_ORDER,
    features: [...ALL_FEATURES, "animated-background"],
    i18n: { ar: { description: "كريمي دافئ وظلال نباتية وضوء حديقة." } },
  },
  {
    id: "velvet-archive",
    name: "Velvet Archive",
    access: "premium",
    description: "Burgundy, black, and antique gold with ceremonial weight.",
    theme: "velvet",
    palette: {
      background: "#12060A",
      surface: "#2A0C14",
      foreground: "#F0E4D0",
      muted: "#B79C86",
      accent: "#B8935A",
    },
    typography: "didone",
    layout: "framed",
    seal: "gold",
    material: "velvet",
    stage: "#160509",
    motionStyle: "curtain-open",
    blockOrder: DEFAULT_ORDER,
    features: [...ALL_FEATURES, "curtain"],
    i18n: { ar: { description: "عنابي وأسود وذهب عتيق بوقار احتفالي." } },
  },
  {
    id: "celestial-letter",
    name: "Celestial Letter",
    access: "premium",
    description: "A midnight composition mapped with quiet stars.",
    theme: "celestial",
    palette: {
      background: "#070A22",
      surface: "#0B1030",
      foreground: "#ECEBF5",
      muted: "#8E93B8",
      accent: "#D8C89A",
    },
    typography: "script-accent",
    layout: "classic",
    seal: "silver",
    material: "celestial",
    stage: "#1D2260",
    motionStyle: "star-drift",
    blockOrder: DEFAULT_ORDER,
    features: [...ALL_FEATURES, "animated-background"],
    i18n: { ar: { description: "تكوين منتصف الليل تزينه نجوم هادئة." } },
  },
  {
    id: "azure-tide",
    name: "Azure Tide",
    access: "premium",
    description: "A luminous blue invitation shaped by light, movement, and water.",
    theme: "azure",
    palette: {
      background: "#0B3670",
      surface: "#124B8F",
      foreground: "#F5FAFF",
      muted: "#E1EEFA",
      accent: "#FFFFFF",
    },
    typography: "editorial-serif",
    layout: "cinematic",
    seal: "silver",
    material: "azure",
    stage: "#C6DCEE",
    motionStyle: "liquid-reveal",
    blockOrder: ["names", "invitation-line", "date", "venue", "map", "rsvp"],
    features: [...ALL_FEATURES, "animated-background"],
    i18n: { ar: { description: "دعوة زرقاء مضيئة يشكّلها الضوء والحركة والماء." } },
  },
];

export const freeTemplates = templates.filter((t) => t.access === "free");
export const premiumTemplates = templates.filter((t) => t.access === "premium");

export function getTemplate(
  listOrId: Template[] | string | null | undefined,
  maybeId?: string | null,
): Template | undefined {
  if (Array.isArray(listOrId)) {
    return maybeId ? listOrId.find((t) => t.id === maybeId) : undefined;
  }
  const id = typeof listOrId === "string" ? listOrId : undefined;
  return id ? templates.find((t) => t.id === id) : undefined;
}
